esp32s2/s3: Fix "error: redefinition of '_PM_timerGetCount'"
In CircuitPython, it is an error to provide two implementations of
_PM_timerGetCount, so this one must be made conditional on !S2 && !S3